addpath('../');

if ~exist('preds4', 'var') || ...
        ~exist('ref_preds', 'var') || ...
        ~exist('preds', 'var') || ...
        ~exist('spinup_stats', 'var')
    load_qg_data
end

exportdir = '~/Projects/doc/mlqg/figs/QG_spectra/';

trunc = 20*365; % truncate initial spinup

fs = 11;
dims = [20,16];

spec_opts = [];
spec_opts.windowsize = 10;
spec_opts.trunc = trunc;
spec_opts.skip = 90;
spec_opts.conf_int = false;
spec_opts.stircol = cols(1,:);

plot_data = {dgen.R*ref_preds{1,1}(trunc:end,:)',...
             preds{1,1}(trunc:end,:)',...
             preds{1,2}(trunc:end,:)',...
             preds{1,3}(trunc:end,:)',...
             preds4{1,2}(trunc:end,:)',...
             preds2{1,2}(trunc:end,:)',...
             preds{1,6}(trunc:end,:)',...
            };


names = {'perfect QG', ...
         'imperfect QG', ...
         'ESN', ...
         'ESNc', ...
         'DMDc', ...
         'correction only', ...
         'ESN+DMDc'};

colors = {cols(1,:), ...
          cols(2,:), ...
          cols(3,:), ...
          cols(4,:), ...
          cols(5,:), ...
          cols(6,:), ...
          cols(7,:)};

f = plot_spectra(qg_c, p, plot_data, names, colors, spec_opts);
exportfig([exportdir, 'results_powerspec.eps'], fs, dims, invert)
%-----------------------------------------------------------------------------
% ROM results

plot_data = {dgen.R*ref_preds{1,1}(trunc:end,:)',...
             preds{1,1}(trunc:end,:)',...
             preds{1,14}(trunc:end,:)',...
             preds{1,15}(trunc:end,:)',...
             preds{1,18}(trunc:end,:)',...
            };

names = {'perfect QG', ...
         'imperfect QG', ...
         'ESN, local POD', ...
         'ESNc, local POD', ...
         'ESN+DMDc, local POD'};

colors = {cols(1,:), ...
          cols(2,:), ...
          cols(3,:), ...
          cols(4,:), ...
          cols(7,:)};
f = plot_spectra(qg_c, p, plot_data, names, colors, spec_opts);
exportfig([exportdir, 'results_powerspec_rom.eps'], fs, dims, invert)
%-----------------------------------------------------------------------------

function [f] = plot_spectra(qg, p, plot_data, names, colors, opts)
    f = [];
    for j = 1:numel(plot_data)
        opts.T = size(plot_data{j},2);
        [f{j}, Pm_ref, Pv_ref] = p.plot_qg_mean_spectrum(qg, plot_data{j}, ...
                                                         opts, '.-', 'color', colors{j});
        hold on
        drawnow
    end
    hold off

    legend([f{:}], names{:}, ...
           'interpreter','latex', ...
           'location', 'southwest');

    xlabel('wavenumber $\|\vec{k}\|_2$','interpreter','latex');
    set(gca,'yticklabels',[])
    set(gca,'xtick',[(3:10),15])
    ylim([1e-4,1e3])
    grid on
end